backend:
  name: git-gateway
  branch: master

media_folder: src/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "select", options: ["User Experience", "Digital Strategy", "Digital Marketing", "Interface Design", "Inclusive Design", "Working in Digital"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/filippoferri-ux/src/static/img/"}

  - name: "cases"
    label: "Cases"
    folder: "src/pages/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-page"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Overview", name: "overview", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/filippoferri-ux/src/static/img/"}
    - {label: "Stakeholders", name: "stakeholders", widget: "list"}
    - {label: "Activities", name: "activities", widget: "list"}
    - {label: Goals, name: goals, widget: list, fields: [{label: Goal, name: goal, widget: string}]}

  - name: "legals"
    label: "Legals"
    folder: "src/pages/legals"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Category", name: "category", widget: "hidden", default: "legals"}

  - name: "pages"
    label: "Pages"
    files:

    - file: "src/pages/index.md"
      label: "Home"
      name: "home"
      fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}
    - file: "src/pages/about/index.md"
      label: "About"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
    - file: "src/pages/products/index.md"
      label: "Products Page"
      name: "products"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Heading, name: heading, widget: string}
        - {label: Description, name: description, widget: string}
        - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
        - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
        - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
        - {label: Full_image, name: full_image, widget: image}
        - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
    - file: "src/pages/digital-strategy/index.md"
      label: "UX Strategy Page"
      name: "strategy"
      fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "strategy-page"}
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Heading, name: heading, widget: string}
      - {label: Description, name: description, widget: string}
    - file: "src/pages/contact/index.md"
      label: "Contact Page"
      name: "contact"
      fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
      - {label: Title, name: title, widget: string}
      - {label: faq, name: faq, widget: list, fields: [{label: Question, name: question, widget: string}, {label: Answer, name: answer, widget: string}]}


